### upload-url
POST http://localhost:3001/asset/upload-url
Content-Type: application/json

{
    "fileName": "image.png",
    "mimeType": "image/png",
    "size": 120202
}


### upload-complete
POST http://localhost:3001/asset/upload-complete/01KVF9VW5W8MYMCKMR90DQ1YXR
Content-Type: application/json


### public-url
GET  http://localhost:3001/asset/public-url/01KVF9VW5W8MYMCKMR90DQ1YXR
Content-Type: application/json


### multipul-public-url
GET  http://localhost:3001/asset/public-url
Content-Type: application/json

{
    "assetIds":["01KVF9VW5W8MYMCKMR90DQ1YXR","01KVABP2ZSW94081VPZD8ZVAVY","01KVAC2ST3A7TCT1TGEYTJGCVD"]
}


### delete
DELETE  http://localhost:3001/asset/01KTCF0W7TMZXEQWQABR2C34YE
Content-Type: application/json


